# Generated by Django 5.0.1 on 2024-01-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehcles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehclebrand', models.CharField(max_length=20)),
                ('vehclenumberplate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20, unique=True)),
                ('Lastname', models.CharField(max_length=20, unique=True)),
                ('Vehcle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehcles')),
            ],
        ),
    ]
