# Generated by Django 5.0.1 on 2024-01-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehcles',
            name='Vehclebrand',
            field=models.CharField(max_length=30),
        ),
    ]
