# Generated by Django 5.0.1 on 2024-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_vehcles_vehclebrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehcles',
            name='Vehclebrand',
            field=models.CharField(max_length=20),
        ),
    ]
