# Generated by Django 5.0.1 on 2024-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_vehcles_vehclebrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Firstname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Lastname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
